apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: srv
  name: srv
spec:
  replicas: 10
  selector:
    matchLabels:
      app: srv
  template:
    metadata:
      labels:
        app: srv
    spec:
      containers:
      - image: nginx
        name: srv
        ports:
        - containerPort: 80


