apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  ports:
  - name: http-5000
    port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    app: server
  type: ClusterIP
