---
apiVersion: v1
kind: ConfigMap
metadata:
  name: util-config
data:
  OTEL_EXPORTER_JAEGER_AGENT_SPLIT_OVERSIZED_BATCHES: "1"
  EXEC_ENV: {{ .Values.execution.environment }}
  PG_USERNAME: {{ .Values.postgres.username }}
  PG_PASSWORD: {{ .Values.postgres.password }}
  PG_SERVER: {{ .Values.postgres.server }}
  PG_SCHEMA: {{ .Values.postgres.dbSchema }}
  PG_PORT: {{ .Values.postgres.port | quote }}
  PG_DATABASES: {{ .Values.pgDatabasesToCreate | quote }}
  PG_SCHEMAS: {{ .Values.pgSchemasToCreate | quote }}
  PG_DB_TEMPLATE_NAME: {{ .Values.postgres.dbTemplateName | quote }}
  KAFKA_PORT: {{ .Values.kafka.server.port | quote }}
  KAFKA_SERVER: {{ .Values.kafka.server.url }}
  KAFKA_TOPIC_SUFFIX: {{ .Values.kafka.topics.suffix }}
  KAFKA_TOPIC_PREFIX: {{ .Values.kafka.topics.prefix }}
  KAFKA_TOPICS: "ST_PENDING,ST_CREATING_VIRTUAL,ST_RESOLVING_DEVICES,ST_RESOLVING_CALENDAR,ST_PENDING_CALENDAR_RETRY,ST_QUEUED,ST_ALLOCATING,ST_NETWORK_RESOLVING,ST_ORCHESTRATING,ST_ACTIVE,ST_RELEASING_NETWORK,ST_RELEASING_DEVICES,ST_RELEASING_DB,ST_RELEASED,controller,IPAM,DHCP,lab-manager,lab-db,history"
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: {{ .Values.kafka.schemaRegistry.bootstrapServers }}

  HTTP_FORCE_CLOSE_TCP: {{ .Values.httpForceCloseTcp | quote }}
  SQL_SERVER: {{ .Values.mysql.server | quote }}
  SQL_USERNAME: {{ .Values.mysql.username | quote }}
  SQL_PASSWORD: {{ .Values.mysql.password | quote }}
  SQL_DATABASE: {{ .Values.mysql.dbToCreate | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  superUserPassword: {{ .Values.postgres.password }}
  replicationUserPassword: laasv2replica
