apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-alt
spec:
  ports:
  - port: {{ .Values.postgres.port }}
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
