---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-utils
  name: test-utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-utils
  template:
    metadata:
      labels:
        app: test-utils
    spec:
      containers:
      - image: {{.Values.testUtils.image.repository}}
        name: test-utils
        command: ["/bin/bash", "-c", "sleep 9999999"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.75"
            memory: "512Mi"
          requests:
            cpu: "0.75"
            memory: "512Mi"
        env:
          - name: EXEC_ENV
            valueFrom:
              configMapKeyRef:
                name: util-config
                key: EXEC_ENV
          - name: KAFKA_TOPIC_SUFFIX
            valueFrom:
              configMapKeyRef:
                name: util-config
                key: KAFKA_TOPIC_SUFFIX
          - name: KAFKA_TOPIC_PREFIX
            valueFrom:
              configMapKeyRef:
                name: util-config
                key: KAFKA_TOPIC_PREFIX
          - name: KAFKA_SERVER
            valueFrom:
              configMapKeyRef:
                name: util-config
                key: KAFKA_SERVER
          - name: KAFKA_PORT
            valueFrom:
              configMapKeyRef:
                name: util-config
                key: KAFKA_PORT
          - name: KAFKA_TOPICS
            valueFrom:
              configMapKeyRef:
                name: util-config
                key: KAFKA_TOPICS
          - name: PG_USERNAME
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: PG_USERNAME
          - name: PG_PASSWORD
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: PG_PASSWORD
          - name: PG_SCHEMA
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: PG_SCHEMA
          - name: PG_DB_TEMPLATE_NAME
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: PG_DB_TEMPLATE_NAME
          - name: PG_SERVER
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: PG_SERVER
          - name: PG_PORT
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: PG_PORT
          - name: PG_DATABASES
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: PG_DATABASES
          - name: PG_SCHEMAS
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: PG_SCHEMAS
          - name: HTTP_FORCE_CLOSE_TCP
            valueFrom:
              configMapKeyRef:
                name: util-config
                key: HTTP_FORCE_CLOSE_TCP
          - name: SQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: SQL_PASSWORD
          - name: SQL_USERNAME
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: SQL_USERNAME
          - name: SQL_SERVER
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: SQL_SERVER
          - name: SQL_DATABASE
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: SQL_DATABASE
          - name: OTEL_EXPORTER_JAEGER_AGENT_SPLIT_OVERSIZED_BATCHES
            valueFrom:
              configMapKeyRef:
                  name: util-config
                  key: OTEL_EXPORTER_JAEGER_AGENT_SPLIT_OVERSIZED_BATCHES
