apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: ops
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: airflow
    targetRevision: 6.1.1
    helm:
      values: |
        image:
          tag: 1.10.10-debian-10-r0
  destination:
    server: https://kubernetes.default.svc
    namespace: ops
  syncPolicy:
    automated:
      selfHeal: false