---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: default
spec:
  destination:
    namespace: deploy1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/jaeger-operator
    repoURL: https://wwwin-github.cisco.com/ngdevx-taas/laasv2_e2e.git
    helm:
      values: |
        enableTracing: true
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
