apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kafka
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.2.13
    helm:
      releaseName: kafka
  destination:
    server: "https://kubernetes.default.svc"
    namespace: deploy1