---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laasv2
  namespace: argocd
spec:
  destination:
    namespace: deploy1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/laasv2
    repoURL: https://wwwin-github.cisco.com/ngdevx-taas/laasv2_e2e.git
    helm:
      values: |
        pgStorageClass: default
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
