---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laasv2
  namespace: argocd
spec:
  destination:
    namespace: deploy1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/laasv2
    repoURL: https://wwwin-github.cisco.com/ngdevx-taas/laasv2_e2e.git
    helm:
      values: |
        pgStorageClass: default
        gateway:
          enable: false
        traefik:
          enable: false
        kafka:
          server: 
            url: kafka.deploy1
    targetRevision: 9b09551f8e2c9ad8fe4d9b43a3026b87b8f1f50f
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
