apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.9.5
    helm:
      releaseName: redis
      parameters:
          - name: global.imageRegistry
            value: dockerhub.cisco.com/docker.io
          - name: replica.replicaCount
            value: 0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: deploy1