helm install -n ${K8S_NS} redis bitnami/redis --set global.imageRegistry=dockerhub.cisco.com/docker.io --set global.storageClass=local-path --set replica.replicaCount=0 &

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.9.5
    helm:
      releaseName: redis
      parameters:
          global:
            imageRegistry: dockerhub.cisco.com/docker.io
          replica:
            replicaCount: 0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: deploy1